=== mikeame1in/xml_test/target/classes/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="https://www.standart-namespace.com/"
        xmlns:tns="https://www.standart-namespace.com/"
        elementFormDefault="qualified">
    <element name="users">
        <complexType>
            <sequence>
                <element name="user" type="tns:User" minOccurs="0" maxOccurs="10"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="User">
        <sequence>
            <element name="id" type="long"></element>
            <element name="nickname" type="string"></element>
        </sequence>
    </complexType>
</schema>

=== mikeame1in/xml_test/src/main/resources/users.xml
<?xml version="1.0" encoding="UTF-8" ?>
<users xmlns="https://www.standart-namespace.com/"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation = "users.xsd">
    <user>
        <id>1</id>
        <nickname>u_111</nickname>
        <name>garry</name>
    </user>
    <user>
        <id>2</id>
        <nickname>u_1212</nickname>
    </user>
</users>
